version: '3.5'

volumes:
  database:

networks:
  network_todo:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - database:/var/lib/mysql
    networks:
      - network_todo

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    networks:
      - network_todo

  app:
    build: ./app/
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./app/:/var/www/html/
    networks:
      - network_todo