version: '3.5'

volumes:
  database:

networks:
  network_todo:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - database:/var/lib/mysql
      - ./app/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - network_todo

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - ${PHP_MY_ADMIN_PORTS}
    environment:
      PMA_HOST: mysql
    networks:
      - network_todo

  app:
    build: ./app/
    restart: always
    ports:
      - ${APP_PORTS}
    volumes:
      - ./app/:/var/www/html/
    networks:
      - network_todo